projects/diary/Diary/Diary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('main.urls')),
]

projects/diary/Diary/main/urls.py
from django.urls import path 
from . import views 

app_name = "main"

urlpatterns = [
    path("index/", views.index, name = "index"), #views.後面就是找views.py裡面的function, function不是在這裡叫, it's django who call the fun, we only need to tell django where the function is 
    path("signin/", views.signin, name= "signin"),
    path("signout/",views.signout, name="signout"),
    path("signup/", views.signup, name = "signup"),
    path("create/", views.create, name = "create"),
    path("update/<int:current_id>", views.update, name = "update"), #可以去抓網址後面的id, id不可能重複, 不管跨不跨user (coz the same database)
    path("delete/<int:current_id>", views.delete, name = "delete")
]

projects/diary/Diary/main/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils import timezone


class Color(models.Model):
    color = models.CharField(max_length = 128)
    
    def __str__(self):
        return self.color

class Diary(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE, null = True)
    title = models.CharField(max_length = 128, null = True) #charfield 純文字
    body = RichTextField(blank = True, null = True)
    created = models.CharField(default = timezone.now, max_length= 128) #because its only text, we can edit it and fix timezone problems
    color = models.ForeignKey(Color, on_delete = models.CASCADE, null = True)
    order = models. DateTimeField(auto_now_add = True, null = True) 

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-order']

projects/diary/Diary/main/views.py
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.models import User
from main.models import Diary, Color
from django.contrib.auth import authenticate,login,logout
from .form import DiaryForm

def index(request): #所有使用者cookie session 包起來
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("main:signin")) #找main裡面的urls.py
    
    search_input = request.GET.get("search-area") or "" #把search area後面的(我們搜尋的東西)抓出來
    
    if search_input: #如果search-area後面有東西
        diarys = Diary.objects.filter(user=request.user,
                                      title__icontains = search_input)

    else: #如果search-area後面沒有東西
        diarys = Diary.objects.filter(user=request.user) #filter的條件是你只能看到自己的diary 要login

    return render(request, "main/index.html",{
        "diarys": diarys,
    })

#有登入才會跑以下
def signin(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy("main:index"))

    error = False
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        #user的 用戶名 and 密碼 已經被存到這兩個參數裡面了
        user=authenticate(request, username=username, password=password)
        
        if user is not None:
            pass
            login(request,user)
            return redirect(reverse_lazy("main:index")) #index就是urls.py裏面name取的名字
        else:
            error = True

    return render(request, "main/signin.html", {
        "error": error #這個"error"是對到signin html 語法的error; 前面是變數的名字 冒號後面是名字對到的value
    })

def signup(request):
    error = False

    if request.user.is_authenticated:
        return redirect (reverse_lazy('main:index'))

    if request.method == "POST":
        username = request.POST["username"] #"username"是input標籤的名字 這個input stuff會打在html 
        password = request.POST['password']
        re_password = request.POST['re_password']

        #一些篩選條件才能讓user創新帳號
        if username == "" or password == "" or re_password == "": #欄位不可以空
            error = "Please fill every box"
        
        elif password != re_password:
            error = "Passwords don't match"

        elif len(User.objects.filter(username = username))!= 0: #no duplicate usernames
            error = "Username already exsist"

        else:
            User.objects.create_user(username = username,password = password).save() #save = 創造
            return redirect (reverse_lazy("main:signin")) #如果創好帳號了就回去登入畫面

    return render(request, "main/signup.html",{
        "error": error
    })
    
    #return redirect(reverse_lazy("main:signin"))
    #if the user is alr signin and still wanna make a new acc, we redict him back to the signin page
    #reverse lazy 可以只給名字 不用講什麼html reverse lazy會幫你直接找urls.py裡面的name


def signout(request):
    if request.user.is_authenticated:  
        logout(request)
    return redirect(reverse_lazy("main:signin"))  #signin 完之後要回到signin頁面

def create (request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("main:signin"))
    
    if request.method == "POST":
        new_title = request.POST["title"]
        new_color = request.POST["color"]
        new_body = request.POST["body"]
        
        if new_color == "":
            Diary(user = request.user, title = new_title, body = new_body).save()
        
        else:
            new_color = Color.objects.get(color = new_color)
            Diary(user = request.user,
                  title = new_title,
                  body = new_body,
                  color = new_color).save()
            
        return redirect(reverse_lazy("main:index"))
    
    colors = Color.objects.all()
    diary_form = DiaryForm() #make object, empty 
    
    return render(request, "main/create.html", {
        "form": diary_form,
        "colors": colors,
    })

def update(request,current_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("main:signin"))
    
    #update diary stuff
    if request.method == "POST":
        new_title = request.POST["title"] #"title"跟html的tag name 一樣
        new_color = request.POST["color"]
        new_body = request.POST["body"]

        Diary.objects.filter(id = current_id, user = request.user).update(title = new_title)
        Diary.objects.filter(id = current_id, user = request.user).update(body = new_body)

        if new_color != "" and new_color is not None:   #updating color is more special cos the user might choose to change color to no color, hence we need to check before updating. 
            new_color = Color.objects.get(color = new_color)
            Diary.objects.filter(id = current_id, user = request.user).update(color = new_color)
        else:
            Diary.objects.filter(id = current_id, user = request.user).update(color = None)

        return redirect(reverse_lazy("main:index"))

    #給user所有他們可以modify的東西
    diary = Diary.objects.get(id = current_id, user = request.user)
    color = Color.objects.all() #they can access to all color
    form = DiaryForm(instance=diary) #空白的位置有之前的日記, not empty

    if form.is_valid():
        form.save() #if have instance, need "save" to change.

    #return diary, color, form stuff so user can update about them
    return render(request, "main/update.html", {
        "diary": diary,
        "colors": color,
        "form": form,
        #name : value
    })

def delete(request,current_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("main:signin"))
    
    if request.method == "POST":
        Diary.objects.get(id = current_id, user = request.user).delete()
        return redirect(reverse_lazy("main:index"))
        

    return render(request, "main/delete.html")

projects/diary/Diary/main/templates/main/create.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Create</title>
        <link href="{% static 'main/style.css' %}" rel="stylesheet">
    </head>

    <body> 
        <div class="nav-container">
            <h1> Jn's Tracker </h1>
        </div>

    <div class="main-container">
        <div class="head-container">
            <h1> 
                User. {{request.user.username}}
            </h1>
            <h2> Create New Note </h2>
        </div>
    

        <div class="diary-container">
            <form method="post">
                {% csrf_token %}
                <!--form.media and as_p 可以生成html-->
                {{ form.media }}
                {{ form.as_p }}

                <select name = "color">

                    <!-- 沒有顏色就是 no color  -->
                    <option value="">No Color</option> 

                    <!-- color裡有多少colors底下的html就跑幾次 -->
                    {% for color in colors %}
                    <option value="{{ color.color }}">{{color.color}}</option> <!--前面的color.color是傳回去的後面是印出來下拉選單的-->
                    {% endfor %}
                </select>

                <br><br>
                <button type="submit" class="submit-button"> Create </button>

                <br><br><br>
                <a href="{% url 'main:index' %}"> Go Home </a>
            </form>

        </div>
    </div>
    </body>
</html>

projects/diary/Diary/main/templates/main/delete.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Delete</title>
        <link href="{% static 'main/style.css' %}" rel="stylesheet">
        
    </head>

    <body> 
        <div class="nav-container">
            <h1> Jn's Tracker</h1>
        </div>

    <div class="main-container">
        <div class="head-container">
            <h1> 
                User. {{request.user.username}}
            </h1>
            <h2> Delete </h2>
        </div>
    

        <div class="diary-container">
            <form method="post">
                {% csrf_token %}

                <h2 class="delete-warning">
                    This action can't be recovered.
                    <br><br>
                    Are you sure you want to proceed?
                </h2>

                <button type="submit" class="submit-button"> Delete </button>

                <br><br><br>
                <a href="{% url 'main:index' %}"> Go Home </a>
            </form>

        </div>
    </div>
    </body>
</html>

projects/diary/Diary/main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link href="{% static 'main/style.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Home</title>
</head>

<body>
    <div class="nav-container">
        <h1>
            Jn's Tracker 
        </h1>
    </div>

    <div class="main-container">
        <div class="head-container">
            <h1 class="display-username">
                User: {{request.user.username}} 
            </h1>

            <form method="get"> 
                <input class="submit-input" type="text" name="search-area" placeholder="Search Title"> 
                <button class="submit-button" type="submit">Search</button>
            </form>
        </div>

        <div class="diary-container">
            {% for diary in diarys%}
            <div>
                <h2 class="color-mark" id="color_mark_{{forloop.counter}}">
                    {{diary.color}}
                </h2>

                <h2 id="created_time_{{ forloop.counter }}">
                    {{diary.created}}
                </h2>
            </div> 

            <h2>
                {{ diary.title}}
            </h2>

            <a href="{% url 'main:update' diary.id %}"> View / Update </a> &nbsp;
            <a href="{% url 'main:delete' diary.id %}"> Delete </a>

            <hr>

            {% empty %}
            <h2>
                No Notes Found..
            </h2>

            {% endfor %}

            <!-- 顯示所有link -->
            <a href ="{% url 'main:create' %}"> Create</a>
            <a href ="{% url 'main:index' %}"> View All Notes</a> 
            <!-- url只有django看得懂 會把網址寫成html然後回傳 -->
            <a href ="{% url 'main:signout' %}"> Logout</a>
        </div>
    </div>
        
    <script>
        // timezone handle
        var count = 0;
        var year = 0, month = 0, day = 0, hour = 0 , minute = 0;
        var created_time, processed_time, formatted_time;
        var offset = new Date().getTimezoneOffset() / 60 //gettimezoneoffset 可以抓你的時區跟UTC時區的差別

        var options = {
            weekday: 'long' , year: 'numeric' , month: 'numeric' , day: 'numeric', 
            month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
        };


        while(true){
        try{
            count += 1;
            id_name = "created_time_" + count;
            created_time = document.getElementById(id_name);
            
            year = parseInt(created_time.innerHTML.substr(21,4)); //4是開始的位子向右多少, (這裡的4就是2024 不知為什麼2024前面很多空格) 
            month = parseInt(created_time.innerHTML.substr(26,2));
            day = parseInt(created_time.innerHTML.substr(29,2));
            hour = parseInt(created_time.innerHTML.substr(32,2));
            minute = parseInt(created_time.innerHTML.substr(35,2));

            processed_time = new Date(year, month-1, day, hour, minute);
            processed_time.setHours(hour-offset); 
            formatted_time = processed_time.toLocaleString("en-US",options);

            created_time.innerHTML = formatted_time;

        }catch{
            break;
        }
    }

        //color mark handle
        count = 0;
        var id_name;
        var color;
        var color_object;

        while(true)

            try{
                
            count += 1 
            id_name = "color_mark_" + count; //javascript可以加兩個不同type

            color_object = document.getElementById(id_name);
            color = color_object.innerHTML;

            color_object.style.backgroundColor = color;
            color_object.innerHTML = "";
        } catch{
            break;
        }
    
    </script>

</body>
</html>

projects/diary/Diary/main/templates/main/signin.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Sign In</title>
        <link href="{% static 'main/style.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    </head>

    <body>
        <div>
            <h1 class="nav-container">
                Jn's Tracker
            </h1>
        </div>

        <div class="main-container">
            <div class="head-container">
                <h1>
                    User: N/A
                </h1>
                
                <h2>
                    Signin Here
                </h2>
            </div>

                <div class="diary-container">
                    <form method="post">
                        {% csrf_token %}

                        {% if error %}
                        <h2 class="error">
                            Error: Incorrect username or password
                        </h2>
                        {% endif %}

                        <h1>
                            Username:
                        </h1>
                        <input type="text" name="username" class="submit-input">
                        <h1>
                            Password:
                        </h1>
                        <input type="password" name="password" class="submit-input">

                        <br>
                        <button type ="submit" class="submit-button">Login</button>

                        <br><br><br>
                        <a href="{% url 'main:signup' %}">Not a member? Create an account here</a>
                    </form>
            </div>
        </div>
    </body>
</html>

projects/diary/Diary/main/templates/main/signup.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link href="{% static 'main/style.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <title>SignUp</title>


    </head>

    <body>
        <div>
            <h1 class="nav-container">
                Jn's Tracker
            </h1>
        </div>

        <div class="main-container">
            <div class="head-container">
                <h1>
                    User: N/A
                </h1>
                
                <h2>
                    Signup Here
                </h2>
            </div>

                <div class="diary-container">
                    <form method="post">
                        {% csrf_token %}

                        {% if error %}
                        <h2 class="error">
                            Error: {{ error }}
                        </h2>
                        {% endif %}

                        <h1>
                            Username:
                        </h1>
                        <input type="text" name="username" class="submit-input">
                        
                        <h1>
                            Password:
                        </h1>
                        <input type="password" name="password" class="submit-input">

                        <h1>
                            Confirm Password:
                        </h1>
                        <input type="password" name="re_password" class="submit-input">

                        <br>
                        <br>
                        <button type ="submit" class="submit-button"> Sign Up </button>

                        <br><br><br>
                        <a href="{% url 'main:signin' %}"> Go back </a>
                    </form>
            </div>
        </div>

    </body>
</html>

projects/diary/Diary/main/templates/main/update.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Update / View</title>
        <link href="{% static 'main/style.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    </head>

    <body> 
        <div class="nav-container">
            <h1> Jn's Tracker</h1>
        </div>

    <div class="main-container">
        <div class="head-container">
            <h1> 
                User. {{request.user.username}}
            </h1>
            <h2> View / Update </h2>
        </div>
    

        <div class="diary-container">
            <form method="post">
                {% csrf_token %}
                <!--form.media and as_p 可以生成html-->
                {{ form.media }}
                {{ form.as_p }}

                <select name = "color">
                    
                    <!--update時下拉選單第一個選項一定是之前選好的那個顏色-->
                    {% if diary.color %}
                    <option value="{{diary.color}}">{{diary.color}}</option>
                    {% else %}
                    <option value="">No Color</option> 
                    {% endif %}

                    <!-- color裡有多少colors底下的html就跑幾次 -->
                    {% for color in colors %}
                    <option value="{{ color.color }}">{{color.color}}</option> <!--前面的color.color是傳回去的後面是印出來下拉選單的-->
                    {% endfor %}

                    <!-- 沒有顏色就是 no color  -->
                    <option value="">No Color</option> 
                </select>

                <br><br>
                <button type="submit" class="submit-button"> Update </button>

                <br><br><br>
                <a href="{% url 'main:index' %}"> Go Home </a>
            </form>

        </div>
    </div>
    </body>
</html>